### PR TITLE
Implement "Clear" Button Functionality 

### PR DESCRIPTION
**Pull request by Rushhaabhhh**
This pull request #11  adds a "Clear" button functionality to the Story List and Word Sentence components, allowing users to easily reset applied filters.

### CODE REVIEW

**Comment by sonisumit7904** [comment]
Hi @Rushhaabhhh ! can you help me, how did you setup this project, All I'm getting is a blank page when I go to localhost:4200 after ng serve.

**Comment by gouravmore** [comment]
@Rushhaabhhh  could you please update the PR description with the video recording of the implementation?

**Comment by gouravmore** [comment]
> Hi @Rushhaabhhh ! can you help me, how did you setup this project, All I'm getting is a blank page when I go to localhost:4200 after ng serve.

@sonisumit7904 To run the config app locally - you need to update the base href="/ " from /all-config-app/
can you try to update the base href from the index.html in following way
- Go to index.html file
- replace `<base href="/all-config-app/">` to=> `<base href="/">`

**Comment by gouravmore** [comment]
Please refer to the following PR for correct implementation
Link: https://github.com/Sunbird-ALL/all-config-app/pull/15

**Pull request closed without merging**
