### PR TITLE
Implemented clear button for clearing filter 

### PR DESCRIPTION
**Pull request by surajgorai2002**
Implemented the clear button functionality that reset all the applied filter to their default setting. Implemented and tested with every possible cases.

Fix For #11 .
PR For #11 

Looking forward for the review.

Capture

### CODE REVIEW

**Comment by sonisumit7904** [comment]
@surajgorai2002 How did you run the project locally, I'm getting blank browser window, on localhost:4200?
This would be a great help and we could work together!

**Comment by surajgorai2002** [comment]
> @surajgorai2002 How did you run the project locally, I'm getting blank browser window, on localhost:4200? This would be a great help and we could work together!

Connect me on LinkedIn. I will help you out!

**Comment by Kumar2004-2009** [comment]
Could you please tell me also how to run this project as I am getting same, a blank page

**Comment by gouravmore** [comment]
@surajgorai2002 could you please update the PR description with the video recording of the implementation?

**Comment by gouravmore** [comment]
@sonisumit7904 @Kumar2004-2009 To run the config app locally - you need to update the base href="/ " from /all-config-app/
can you try to update the base href from the index.html in following way

Go to index.html file
replace <base href="/all-config-app/"> to=> <base href="/">

**Comment by VedantKhairnar** [comment]
Hello @surajgorai2002  ,
Thanks for your contribution.
As part of Augtoberfest, we want to reward you for your contributions, so pls fill out [this form](https://forms.gle/VBDUPWMYcZEbmVrQ9) by 19th Sept.
Thanks.

**Pull request merged**
